name = "HEPRecipes"
uuid = "13ebb339-f092-412f-a286-f7290b551f86"
authors = ["Misha Mikhasenko <mikhail.mikhasenko@gmail.com>"]
version = "0.1.0"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots"]
